Update production_automation.yml

diff --git a/.github/workflows/production_automation.yml b/.github/workflows/production_automation.yml
--- a/.github/workflows/production_automation.yml
+++ b/.github/workflows/production_automation.yml
@@ -1,19 +1,16 @@
 name: Monthly MLOps Pipeline
 
+permissions:
+  contents: read
+  packages: write
+  issues: write
+
 on:
   # Run at midnight on the first day of every month
   schedule:
     - cron: '0 0 1 * *'
   # Allow manual triggers
   workflow_dispatch:
-  # Run on push to main (for testing)
-  # push:
-  #   branches:
-  #     - main
-  #   paths:
-  #     - 'src/**'
-  #     - 'scripts/**'
-  #     - '.github/workflows/production_automation.yml'
 
 jobs:
   unit-test:
@@ -52,80 +49,24 @@ jobs:
         poetry run flake8 .
         poetry run mypy .
 
-  # # Push docker images to DockerHub (Optional)
-  # docker-build-push:
-  #   if: |
-  #     github.event_name == 'workflow_dispatch' || 
-  #     (github.event_name == 'push' && github.ref == 'refs/heads/main')
-
-  #   runs-on: ubuntu-latest
-
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v3
-
-  #     - name: Set up Docker Buildx
-  #       uses: docker/setup-buildx-action@v3
-
-  #     - name: Log in to DockerHub
-  #       uses: docker/login-action@v3
-  #       with:
-  #         username: ${{ secrets.DOCKER_USERNAME }}
-  #         password: ${{ secrets.DOCKER_PASSWORD }}
-
-  #     - name: Build and push mlflow image
-  #       uses: docker/build-push-action@v5
-  #       with:
-  #         context: .
-  #         file: ./Dockerfile.mlflow
-  #         push: true
-  #         tags: ${{ secrets.DOCKER_USERNAME }}/employee-attrition-2-mlflow-server:latest
-  #         cache-from: type=gha
-  #         cache-to: type=gha,mode=max
-  #         
-  #     - name: Build and push api image
-  #       uses: docker/build-push-action@v5
-  #       with:
-  #         context: .
-  #         file: ./Dockerfile
-  #         push: true
-  #         tags: ${{ secrets.DOCKER_USERNAME }}/employee-attrition-2-api:latest
-  #         cache-from: type=gha
-  #         cache-to: type=gha,mode=max
-
-  #     - name: Build and push frontend image
-  #       uses: docker/build-push-action@v5
-  #       with:
-  #         context: .
-  #         file: ./Dockerfile.frontend
-  #         push: true
-  #         tags: ${{ secrets.DOCKER_USERNAME }}/employee-attrition-2-frontend:latest
-  #         cache-from: type=gha
-  #         cache-to: type=gha,mode=max
-
-  #     - name: Build and push drift image
-  #       uses: docker/build-push-action@v5
-  #       with:
-  #         context: .
-  #         file: ./Dockerfile.drift
-  #         push: true
-  #         tags: ${{ secrets.DOCKER_USERNAME }}/employee-attrition-2-drift-api:latest
-  #         cache-from: type=gha
-  #         cache-to: type=gha,mode=max
-
-  run_pipeline:
+  run-pipeline:
     if: |
       github.event_name == 'schedule' || 
-      github.event_name == 'workflow_dispatch' || 
-      (github.event_name == 'push' && github.ref == 'refs/heads/main')
+      github.event_name == 'workflow_dispatch'
 
     runs-on: ubuntu-latest
-    # env: # Set env vars for all steps
-    #     MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
-    #     DATABASE_URL_PYMSSQL: ${{ secrets.DATABASE_URL_PYMSSQL }}
-    #     DATABASE_URL_PYODBC: ${{ secrets.DATABASE_URL_PYODBC }}
-    #     DRIFT_API_URL: ${{ secrets.DRIFT_API_URL }} # Ensure this secret is set in GitHub
-    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+
+    env: # Set env vars for all steps
+      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
+      DATABASE_URL_PYMSSQL: ${{ secrets.DATABASE_URL_PYMSSQL }}
+      DATABASE_URL_PYODBC: ${{ secrets.DATABASE_URL_PYODBC }}
+      DRIFT_API_URL: ${{ secrets.DRIFT_API_URL }} # Ensure this secret is set in GitHub
+      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+
+    outputs:
+      feature_drift_detected: ${{ steps.feature_drift.outputs.drift_detected }}
+      prediction_drift_detected: ${{ steps.prediction_drift.outputs.drift_detected }}
+
 
     steps:
     - uses: actions/checkout@v3
@@ -141,23 +82,26 @@ jobs:
         pip install poetry
         poetry install --only main # Use --only main for consistency
     
-    # Hardcoded env if github secrets are not set
-    - name: Set up environment
-      run: |
-        echo "MLFLOW_TRACKING_URI=http://127.0.0.1:5001" >> $GITHUB_ENV
-        echo "DATABASE_URL_PYMSSQL=mssql+pymssql://myuser:Password1!@employeeattrition2.database.windows.net/EmployeeAttrition" >> $GITHUB_ENV
-        echo "DATABASE_URL_PYODBC=mssql+pyodbc://myuser:Password1!@employeeattrition2.database.windows.net/EmployeeAttrition?driver=ODBC+Driver+17+for+SQL+Server" >> $GITHUB_ENV
-        echo "DRIFT_API_URL=http://drift-api:8000" >> $GITHUB_ENV
-
-    # - name: Build and run services with Docker Compose
+    # # Hardcoded env if github secrets are not set
+    # - name: Set up environment
     #   run: |
-    #     docker-compose up -d --build
-    #     sleep 15  # Give containers some time to start
-    #     docker ps  # Check running containers
-    #     if [ $? -ne 0 ]; then
-    #       echo "::error::Docker Compose failed to start."
-    #       exit 1
-    #     fi
+    #     echo "MLFLOW_TRACKING_URI=http://127.0.0.1:5001" >> $GITHUB_ENV
+    #     echo "DATABASE_URL_PYMSSQL=mssql+pymssql://myuser:Password1!@employeeattrition2.database.windows.net/EmployeeAttrition" >> $GITHUB_ENV
+    #     echo "DATABASE_URL_PYODBC=mssql+pyodbc://myuser:Password1!@employeeattrition2.database.windows.net/EmployeeAttrition?driver=ODBC+Driver+17+for+SQL+Server" >> $GITHUB_ENV
+    #     echo "DRIFT_API_URL=http://drift-api:8000" >> $GITHUB_ENV
+
+    - name: Build and run services with Docker Compose
+      continue-on-error: true
+      run: |
+        docker-compose up -d --build
+        sleep 15
+        docker ps
+        if [ $? -ne 0 ]; then
+          echo "::error::Docker Compose failed to start."
+          echo "status=failed" >> $GITHUB_OUTPUT
+        else
+          echo "status=success" >> $GITHUB_OUTPUT
+        fi
 
     # Step 1: Run batch prediction
     # Assuming batch_predict.py saves predictions and maybe features?
@@ -220,7 +164,7 @@ jobs:
         # Save new reference data after retraining
         echo "Saving new reference data and predictions..."
         poetry run python scripts/save_reference_data.py
-        echo "::set-output name=retrained::true"
+        echo "retrained=true" >> $GITHUB_OUTPUT
         
     # Step 5: Create summary issue
     - name: Create summary issue
@@ -275,3 +219,73 @@ jobs:
             body: summary,
             labels: [`automation-${context.job.status === 'success' ? 'success' : 'failed'}`, retrained ? 'retrained' : 'no-drift']
           }); 
+
+  # Push docker images to DockerHub (Optional)
+  docker-build-push:
+    needs: run-pipeline
+    if: |
+      needs.run-pipeline.outputs.feature_drift_detected == 'true' ||
+      needs.run-pipeline.outputs.prediction_drift_detected == 'true'
+
+    runs-on: ubuntu-latest
+
+    env:
+      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Log in to DockerHub
+        uses: docker/login-action@v3
+        with:
+          username: $DOCKER_USERNAME
+          password: $DOCKER_PASSWORD
+
+      - name: Build and push mlflow image
+        continue-on-error: true
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: ./Dockerfile.mlflow
+          push: true
+          tags: $DOCKER_USERNAME/employee-attrition-2-mlflow-server:latest
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+          
+      - name: Build and push api image
+        continue-on-error: true
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: ./Dockerfile
+          push: true
+          tags: $DOCKER_USERNAME/employee-attrition-2-api:latest
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+
+      - name: Build and push frontend image
+        continue-on-error: true
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: ./Dockerfile.frontend
+          push: true
+          tags: $DOCKER_USERNAME/employee-attrition-2-frontend:latest
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+
+      - name: Build and push drift image
+        continue-on-error: true
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: ./Dockerfile.drift
+          push: true
+          tags: $DOCKER_USERNAME/employee-attrition-2-drift-api:latest
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
